---
name: Bitwarden CI/CD

on:
  pull_request:
    branches:
      - '**'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Latest
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    - name: Setup Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip3 install pipenv
        pipenv install --dev

    - name: Run Unit Tests
      run: pipenv run pytest
